// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(SollicitatieContext))]
    [Migration("20260330172241_UpdateSeedLinks")]
    partial class UpdateSeedLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("API.Models.BedrijfInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bedrijven");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Locatie = "Gent",
                            Naam = "Eniris"
                        },
                        new
                        {
                            Id = 2,
                            Locatie = "Gent",
                            Naam = "Nuanso"
                        });
                });

            modelBuilder.Entity("API.Models.Sollicitatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedrijfInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BedrijfInfoId");

                    b.ToTable("Sollicitaties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedrijfInfoId = 1,
                            Datum = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://eniris.io/",
                            Notities = "Vorige stageplek",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BedrijfInfoId = 2,
                            Datum = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "https://www.nuanso.io/",
                            Notities = "AI advertising project",
                            Status = 2
                        });
                });

            modelBuilder.Entity("API.Models.Sollicitatie", b =>
                {
                    b.HasOne("API.Models.BedrijfInfo", "BedrijfInfo")
                        .WithMany()
                        .HasForeignKey("BedrijfInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BedrijfInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
