// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(SollicitatieContext))]
    partial class SollicitatieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("API.Models.BedrijfInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bedrijven", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Locatie = "Gent",
                            Naam = "Eniris"
                        },
                        new
                        {
                            Id = 2,
                            Locatie = "Gent",
                            Naam = "Nuanso"
                        });
                });

            modelBuilder.Entity("API.Models.Sollicitatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedrijfInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Notities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BedrijfInfoId");

                    b.ToTable("Sollicitaties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedrijfInfoId = 1,
                            Datum = "2026-03-10 00:00:00",
                            Link = "https://eniris.io/",
                            Notities = "Vorige stageplek",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BedrijfInfoId = 2,
                            Datum = "2026-03-15 00:00:00",
                            Link = "https://www.nuanso.io/",
                            Notities = "AI advertising project",
                            Status = 2
                        });
                });

            modelBuilder.Entity("API.Models.Sollicitatie", b =>
                {
                    b.HasOne("API.Models.BedrijfInfo", "BedrijfInfo")
                        .WithMany()
                        .HasForeignKey("BedrijfInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BedrijfInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
